spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
gcs:
  bucket-name: own_my_geul_bucket
  key-file: /Users/maeng/desktop/gcp/ownmygeul-4719db2125f4.json