spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
gcs:
  bucket-name: own_my_geul_bucket
  key-file: /Users/maeng/desktop/gcp/ownmygeul-4719db2125f4.json


custom:
  ai-server-url: ${AI_SERVER_URL}


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**