on:
  pull_request:
    branches:
      - dev
    paths:
      - omg-springboot-app
  push:
    branches:
      - dev
    paths:
      - omg-springboot-app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo This is test
    
