on:
  pull_request:
    types:
      - closed
    branches:
      - dev
    paths:
      - 'omg-springboot-app/**'
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
