on:
  pull_request:
    branches:
      - dev
    types:
      - closed
  push:
    branches:
      - dev
jobs:
  if_merged:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
